import "~/styles/globals.css";

import { SpeedInsights } from '@vercel/speed-insights/next';
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { AuthSessionProvider } from "./components/layout/providers";


import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create App Chat Demo",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.png" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <AuthSessionProvider>
          <TRPCReactProvider>{children}</TRPCReactProvider>
          <SpeedInsights />
        </AuthSessionProvider>
      </body>
    </html>
  );
}
